### ISSUE TITLE
Error when linting models

### ISSUE THREAD

**Issue by gilmrjc** [landscapeio/pylint-django#104]
When linting models I get the following:

```
KeyError: 'Model'
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 364, in getattr
    return [self.import_module(name, relative_only=True)]
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 425, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/lib/python2.7/site-packages/astroid/manager.py", line 160, in ast_from_module_name
    return self.ast_from_file(filepath, modname, fallback=False)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/lib/python2.7/site-packages/astroid/manager.py", line 112, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/lib/python2.7/site-packages/astroid/builder.py", line 134, in file_build
    module = self._data_build(data, modname, path)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/lib/python2.7/site-packages/astroid/builder.py", line 177, in _data_build
    module = rebuilder.visit_module(node, modname, node_file, package)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/lib/python2.7/site-packages/astroid/rebuilder.py", line 150, in visit_module
    return self._transform(newnode)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/lib/python2.7/site-packages/astroid/manager.py", line 337, in transform
    ret = transform_func(node)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/lib/python2.7/site-packages/pylint_django/transforms/__init__.py", line 37, in set_fake_locals
    module.locals[class_name].extend(fake.locals[class_name])
```

I'm using Django 1.11 but also do not work with Django 1.10

I fixed it by adding this lines to the transform `__init__.py` and copying the django_db_models transform file to fake the new packages:

```python
_add_transform('django.db.models.base', 'Model')
_add_transform('django.db.models.manager', 'Manager')
```

I'm sorry I can't send a patch because I don't know how to handle older version to avoid breaking but this would work with the most recent versions of Django.

My requirements:

```
astroid==1.3.8
Django==1.11
pylint==1.4.5
pylint-django==0.7.2
pylint-plugin-utils==0.2.6
```

**Comment by atodorov** [comment]
Can't reproduce with latest Django 1.11 nor latest Django 2.0:
https://travis-ci.org/landscapeio/pylint-django/builds/331129687
