### ISSUE TITLE
tests: ManyFieldsForm: Module 'django.forms' has no 'IPAddressField' member

### ISSUE THREAD

**Issue by danstender** [landscapeio/pylint-django#62]
Hi, I've got that here with 0.7.1:
```
$ PYTHONPATH=. python test/test_func.py 
..................F
======================================================================
FAIL: test_functionality (pylint.testutils.LintTC)
file test of input file "func_noerror_form_fields" (LintTC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pylint/testutils.py", line 323, in test_functionality
    self._test(tocheck)
  File "/usr/lib/python2.7/dist-packages/pylint/testutils.py", line 298, in _test
    self._check_result(self.linter.reporter.finalize())
  File "/usr/lib/python2.7/dist-packages/pylint/testutils.py", line 282, in _check_result
    got.strip()+'\n')
AssertionError: '\n' != "E: 24:ManyFieldsForm: Module 'django.forms' has no 'IPAddressField' member\n"
- 
+ E: 24:ManyFieldsForm: Module 'django.forms' has no 'IPAddressField' member
----------------------------------------------------------------------
Ran 19 tests in 2.952s
```
The build Django is 0.9.1 (IPAdressFiled dropped?).

Thanks,
DS

**Comment by carlio** [comment]
Looks like the IPAddressField moved to GenericIPAddressField some time ago. I fixed this as part of https://github.com/landscapeio/pylint-django/commit/e044f83b5db0148b11bd89abfb5c2bb084de0247 by making it use whichever happens to be available. Perhaps not the most elegant solution but it works!
