### ISSUE TITLE
AttributeError: 'Module' object has no attribute '_locals'

### ISSUE THREAD

**Issue by d33tah** [landscapeio/pylint-django#71]
```
$ pylint  --load-plugins pylint_django projectname | egrep '^\*|^E:'
Traceback (most recent call last):
  File "/usr/bin/pylint", line 9, in <module>
    load_entry_point('pylint==1.4.3', 'console_scripts', 'pylint')()
  File "/usr/lib/python2.7/site-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 1332, in __init__
************* Module projectname.external
************* Module projectname.SECRET_KEY
    linter.check(args)
  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 747, in check
    self._do_check(files_or_modules)
  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 869, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 946, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 874, in walk
    self.walk(child)
  File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 874, in walk
    self.walk(child)
  File "/usr/lib/python2.7/site-packages/pylint/utils.py", line 871, in walk
    cb(astroid)
  File "/usr/lib/python2.7/site-packages/pylint_plugin_utils/__init__.py", line 54, in augment_func
    augmentation(chain, node)
  File "/usr/lib/python2.7/site-packages/pylint_plugin_utils/__init__.py", line 127, in do_suppress
    chain()
  File "/usr/lib/python2.7/site-packages/pylint_plugin_utils/__init__.py", line 53, in chain
    old_method(node)
  File "/usr/lib/python2.7/site-packages/pylint/checkers/base.py", line 1021, in visit_assname
    if isinstance(safe_infer(ass_type.value), astroid.Class):
  File "/usr/lib/python2.7/site-packages/pylint/checkers/utils.py", line 92, in safe_infer
    value = next(inferit)
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 351, in wrapper
    for node in func(*args, **kwargs):
  File "/usr/lib/python2.7/site-packages/astroid/inference.py", line 196, in infer_callfunc
    for infered in callee.infer_call_result(self, callcontext):
  File "/usr/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 835, in infer_call_result
    for infered in returnnode.value.infer(context):
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 86, in cache_generator
    for result in generator:
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 351, in wrapper
    for node in func(*args, **kwargs):
  File "/usr/lib/python2.7/site-packages/astroid/inference.py", line 190, in infer_callfunc
    for callee in self.func.infer(context):
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 86, in cache_generator
    for result in generator:
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 124, in _infer_stmts
    for infered in stmt.infer(context):
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 86, in cache_generator
    for result in generator:
  File "/usr/lib/python2.7/site-packages/astroid/bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/lib/python2.7/site-packages/astroid/inference.py", line 229, in infer_from
    module = self.do_import_module()
  File "/usr/lib/python2.7/site-packages/astroid/mixins.py", line 107, in do_import_module
    return mymodule.import_module(modname, level=level)
  File "/usr/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 431, in import_module
    return MANAGER.ast_from_module_name(modname)
  File "/usr/lib/python2.7/site-packages/astroid/manager.py", line 160, in ast_from_module_name
    return self.ast_from_file(filepath, modname, fallback=False)
  File "/usr/lib/python2.7/site-packages/astroid/manager.py", line 112, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/lib/python2.7/site-packages/astroid/builder.py", line 134, in file_build
    module = self._data_build(data, modname, path)
  File "/usr/lib/python2.7/site-packages/astroid/builder.py", line 177, in _data_build
    module = rebuilder.visit_module(node, modname, node_file, package)
  File "/usr/lib/python2.7/site-packages/astroid/rebuilder.py", line 150, in visit_module
    return self._transform(newnode)
  File "/usr/lib/python2.7/site-packages/astroid/manager.py", line 337, in transform
    ret = transform_func(node)
  File "/usr/lib/python2.7/site-packages/pylint_django/transforms/__init__.py", line 29, in set_fake_locals
    module._locals[class_name] = fake._locals[class_name]  # pylint: disable=protected-access
AttributeError: 'Module' object has no attribute '_locals'
```

**Comment by carlio** [comment]
If you try with latest master, I think this should work? Thanks to this commit: https://github.com/landscapeio/pylint-django/commit/efb3f928e4ab2eb9b48cbb2e150481da99745135

Please reopen if not!
